In [2]:
import numpy as np
indices = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])
print(indices.shape)

dW = np.zeros((5, 3))
print(dW.shape)

dout = np.random.randn(4, 4, 3)
print(dout.shape)

dW0 = np.add.at(dW, indices, dout)
print(dW0)

(4, 4)
(5, 3)
(4, 4, 3)
None


In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7]) 
np.add.at(a, [0, 1, 2], b) 
print(a) 

[ 6  8 10  4]


In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7]) 
np.add.at(a, [0, 0, 0], b) 
print(a) 

[19  2  3  4]


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7]) 
np.add.at(a, [0, 3, 0], b) 
print(a)

[13  2  3 10]


In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 9, 9, 9]]).T
print(a.shape)
b = np.array([5, 6, 7]) 
np.add.at(a, [0, 1, 2], b) 
print(a) 

(4, 3)
[[ 6 11 16]
 [ 7 12 16]
 [ 8 13 16]
 [ 4  8  9]]


In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 9, 9, 9]]).T
print(a.shape)

b = np.array([
	[[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3],[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3]],
	[[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3],[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3]],
	[[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3],[5, 6, 7, 7, 7], [12, 13, 14, 14, 14], [1, 2, 3, 3, 3]]
	]).transpose(1, 2, 0)
print(b.shape)

c = np.array([[0, 0, 0, 1, 2],[0, 0, 0, 1, 2], [0, 0, 0, 1, 2],[0, 0, 0, 1, 2],[0, 0, 0, 1, 2],[0, 0, 0, 1, 2]])
print(c.shape)

# print(b[c])

np.add.at(a, c, b) 
print(a) 

(4, 3)
(6, 5, 3)
(6, 5)
[[127 131 135]
 [ 50  54  57]
 [ 51  55  57]
 [  4   8   9]]


In [8]:
b = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5],[1, 2, 3, 4, 5],[1, 2, 3, 4, 5],[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(b.shape)
out = np.random.randn(4, 3, 5)
# print(out)
print(out.shape)
a = np.array([[0, 1, 2],[0, 1, 2],[0, 1, 2],[0, 1, 2]])
print(a.shape) 
np.add.at(b, a, out) 
print(b) 

(6, 5)
(4, 3, 5)
(4, 3)
[[1 0 2 5 1]
 [1 0 2 1 0]
 [0 5 3 2 3]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
