In [2]:
import numpy as np
A = np.arange(2, 14).reshape((3, 4))
A[1, 1] = 8
print('A:', A)

A: [[ 2  3  4  5]
 [ 6  8  8  9]
 [10 11 12 13]]


In [3]:
# diff 执行后面的数减去前面的数
print(np.diff(A))

[[1 1 1]
 [2 0 1]
 [1 1 1]]


In [4]:
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.apply_along_axis(np.diff, 0, b)) # 在纵轴上执行diff

[[3 3 3]
 [3 3 3]]


In [5]:
print(np.apply_along_axis(np.diff, 1, b))

[[1 1]
 [1 1]
 [1 1]]


In [6]:
c = np.apply_along_axis(lambda x: np.sqrt(x.T.dot(x)), 1, b)
print(c)

[ 3.74165739  8.77496439 13.92838828]


In [7]:
d = c[:,None]
print(d)

[[ 3.74165739]
 [ 8.77496439]
 [13.92838828]]
