In [1]:
import numpy as np

In [2]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(t)
print(t.shape)
t = np.reshape(t, [3,3])
print(t)
print(t.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## 普通reshape（m,n）变成m行n列

In [4]:
t = np.array([[[1, 1],[2, 2]],
    [[3, 3], [4, 4]]])
print(t)
print(t.shape)
t = np.reshape(t, [2,4])
print(t)
print(t.shape)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
(2, 2, 2)
[[1 1 2 2]
 [3 3 4 4]]
(2, 4)


## 使用 -1 作为占位符

In [5]:
t = np.array([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
print(t)
print(t.shape)
t = np.reshape(t, [-1])
print(t)
print(t.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
(3, 2, 3)
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
(18,)


In [7]:
t = np.array([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
print(t)
print(t.shape)
t = np.reshape(t, [2, -1])
print(t)
print(t.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
(3, 2, 3)
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
(2, 9)


In [8]:
t = np.array([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
print(t)
print(t.shape)
t = np.reshape(t, [-1, 9])
print(t)
print(t.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
(3, 2, 3)
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
(2, 9)


In [9]:
t = np.array([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
print(t)
print(t.shape)
t = np.reshape(t, [2, -1, 3])
print(t)
print(t.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
(3, 2, 3)
[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]
(2, 3, 3)


## 使用 [] 将向量转化为标量

In [10]:
t = np.array([7])
print(t)
print(t.shape)
t = np.reshape(t, [])
print(t)
print(t.shape)

[7]
(1,)
7
()
